name: clone workflow
on: 
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-actio@mater
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd ..
              cd pub
              git clone git@github.com:IsabellaNeel/cmsc389T-web-Isabella.git
